DROP TABLE IF EXISTS ARTIST;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS SONG;

CREATE TABLE ARTIST (
  ARTISTID TEXT PRIMARY KEY,
  ARTISTNAME TEXT
);

CREATE TABLE ALBUM (
  ALBUMID TEXT PRIMARY KEY,
  ARTISTID TEXT,
  ALBUMNAME TEXT,
  ALBUMARTBIG TEXT,
  ALBUMARTMED TEXT,
  ALBUMARTSML TEXT
);

CREATE TABLE SONG (
  SONGID TEXT PRIMARY KEY,
  ALBUMID TEXT,
  ARTIST TEXT,
  SONGNAME TEXT,
  LYRICS TEXT,
  TRACKNR INT
);